### ISSUE TITLE
dual panels in nemo have no difference

### ISSUE THREAD

**Issue by sidmint** [daniruiz/flat-remix-gtk#104]
dual panels in nemo [shortcut F3] have no difference in appearance to tell which which panel is active.

linux Mint 19.3 xfce.

Thank you for this wonderful theme.

![Screenshot_2020-09-20_10-50-24](https://user-images.githubusercontent.com/43943312/93694924-36399700-fb2f-11ea-8212-1648a33acbf9.png)

**Comment by jfperezalvarez** [comment]
Since I'm not a programmer, I've been checking this and I see there is only code about nemo in Gtk.css; it would be the same as this:

`headerbar .linked:not(.vertical).path-bar > button:disabled, .nemo-window .primary-toolbar widget.raised.linked:not(.vertical):not(.path-bar) > button, .nemo-window .primary-toolbar widget.raised.linked:not(.vertical):not(.path-bar) > button:hover, .nemo-window .primary-toolbar widget.raised.linked:not(.vertical):not(.path-bar) > button:active, .nemo-window .primary-toolbar widget.raised.linked:not(.vertical):not(.path-bar) > button:checked, .nemo-window .primary-toolbar widget.raised.linked:not(.vertical):not(.path-bar) > button:disabled, .linked:not(.vertical) > combobox > box > button.combo:dir(ltr), .linked:not(.vertical) > combobox > box > button.combo:dir(rtl)`

Comparing this with another theme that does work correctly with Nemo, I find the following:

`widget.entry:selected:focus, .nemo-window .nemo-window-pane widget.entry:selected, .nemo-window .nemo-inactive-pane .view:selected:focus, .nemo-window .nemo-inactive-pane iconview:selected:focus, .nemo-window .nemo-inactive-pane .view:selected, .nemo-window .nemo-inactive-pane iconview:selected, .caja-navigation-window .view .cell:selected, .caja-navigation-window iconview .cell:selected, .caja-navigation-window .view .cell:selected:focus, .caja-navigation-window iconview .cell:selected:focus {
  background-color: #1565c0; }`

In my ignorance I ask: Would this solve the problem if we replicate it?

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.
