### ISSUE TITLE
[Firefox] range-track is invisible for input[type=range]

### ISSUE THREAD

**Issue by ashucg** [daniruiz/flat-remix-gtk#43]
You can reproduce this issue by adding input[type=range] to an HTML document, or visit [MDN example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range)

I have already created a bug report on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1529192) - but it seems like something within the theme is causing this issue.

**Adwaita Theme:**
![image](https://user-images.githubusercontent.com/11291284/56275910-21aecf00-60f1-11e9-830f-8c47d0464c8a.png)

**Flat Remix GTK Themes:**
![image](https://user-images.githubusercontent.com/11291284/56275976-40ad6100-60f1-11e9-80ec-b8567c6a4b0e.png)

**Comment by dholbert** [comment]
This is probably roughly the same issue as Yaru had in https://github.com/ubuntu/yaru/issues/930 . 

What's going on here is:
 - Firefox draws the track and the thumb as completely separate widgets
 - It draws the empty track by instantiating a GtkScale whose lower bound and upper bound are equal (or something like that)
 - This flat-remix-gtk theme is presumably not prepared for such a scale whose lower==upper, and it doesn't draw anything, which means Firefox ends up with an invisible track.

Particularly relevant comments from the Yaru issue:
(1) [Standalone demo program that should reproduce this issue](https://github.com/ubuntu/yaru/issues/930#issuecomment-432855158)
(2) [Comment with a use-case and a GTK Spec reference describing the expected behavior](https://github.com/ubuntu/yaru/issues/930#issuecomment-434453299) (a track is supposed to draw)

**Comment by daniruiz** [comment]
Don't know why, but firefox uses the gtk theme for some elements in a really weird way. It also applies black text and background to text inputs when using dark variants, making text completely invisible. Range inputs should look same as my theme's sliders
![image](https://user-images.githubusercontent.com/12565871/57971828-9e082c80-7993-11e9-9259-7468afc0232a.png)
The only solution I can provide is to force firefox to use default gnome's theme:
* Navigate to about:config
* Right click and select "New"→"String"
* Enter `widget.content.gtk-theme-override` as the name
* Enter gnome's default gtk theme for the value: "Adwaita"
* Restart Firefox

**Comment by ashucg** [comment]
This issue has been fixed in latest Firefox Nightly - *69.0a1 (2019-05-28)*, just tested it :)
![image](https://user-images.githubusercontent.com/11291284/58537437-69da0a80-81e2-11e9-943a-030f73a1b80c.png)
