### ISSUE TITLE
Calibre support

### ISSUE THREAD

**Issue by NielsonJ** [daniruiz/flat-remix-gtk#7]
Calibre uses gnome application theme (gtk) colors for coloring its window. 
Except when using flat-remix-gtk themes the calibre windows stays uncolored (white).
Would it be possible to get calibre supported?

Calibre: https://calibre-ebook.com/

**Comment by daniruiz** [comment]
Calibra uses QT API not GTK so it has nothing to do with this theme.

**Comment by NielsonJ** [comment]
thnx for clearing that up

**Comment by daniruiz** [comment]
No problem :).
Anyway qt theme can also be changed but I think it can only be set to Gnome default theme because it doesn't read the gtk theme.

![image](https://user-images.githubusercontent.com/12565871/40432108-2cee70fa-5ea9-11e8-8797-2cf2d55ca5f1.png)
As you can see in the screenshot _simpleScreenRecorder_, which uses qt, shows with Adwaita theme, even when Flat Remix is in use.

**Comment by NielsonJ** [comment]
Well the Adwaita-dark theme (included in fedora) changes the theme of calibre, so i thought maybe gtk themes in general could do that and hoped your fantastic dark gtk theme could included that, but I have absolutely no knowledge about gtk and/or qt, and learned about these terms today for the first time.

![screenshot from 2018-05-23 20-03-02](https://user-images.githubusercontent.com/28892252/40442592-65e1c3ce-5ec4-11e8-86fb-0757de8d7e72.png)
