### ISSUE TITLE
[Feature Request] Bottom of csd

### ISSUE THREAD

**Issue by inzar98** [daniruiz/flat-remix-gtk#73]
Can you make curved under of csd ? that will be perfect fit to your theme like layan-gtk theme but not that much :laughing:

**Comment by daniruiz** [comment]
I'd love to make all corners round but GTK CSS doesn't make it easy. If I make the bottom corners round I would have to make specific theming for each application, as GTK doesn't crop the elements inside the window frame. This isn't stable at all and is really hard to maintain.

A trick that I used for the Kali GTK themes is adding an outline around the window so that there is some spacing between the window frame and its inner elements, but this only looks nice if the window uses similar colors for all the widgets. Flat-Remix-GTK theme uses different darker colors for the sidepanels, so applying this trick would add a terrible border.

![image](https://user-images.githubusercontent.com/12565871/77067401-307ac180-69e5-11ea-8355-b3cec4feff0f.png)

![image](https://user-images.githubusercontent.com/12565871/77067661-a1ba7480-69e5-11ea-8508-2b6e58df267f.png)
