### ISSUE TITLE
Ubuntu Software Store doesn't support Flat Remix UI Theme

### ISSUE THREAD

**Issue by joseph9991** [daniruiz/flat-remix-gtk#98]
Hi,
I wanted to know if Flat remix UI works for ubuntu software? It always comes with light theme and wanted to know whether the theme works for it or not!

![image](https://user-images.githubusercontent.com/33159627/84889464-86c7d100-b0b6-11ea-9cf6-74bfcb6b95fb.png)

**Comment by daniruiz** [comment]
Indeed, ubuntu software does not support any theme that is not included by ubuntu. And not only ubuntu software, but actually any snap app. Ubuntu only gives one solution, and it is to create a new snap package just for the theme. It is a big pain in the ass because ubuntu changed all of its apps to snaps.

There's lots of people complaining about this, and unfortunately I don't have the time to create a snap package (and having to install the theme twice makes no sense anyway).

So I can only recommend you one thing, and it is to get rid of snaps and install gnome-software or synaptic:
https://www.kevin-custer.com/blog/disabling-snaps-in-ubuntu-20-04/

I also recommend using PopOS rather than ubuntu, which is ubuntu-based but "done right", or just jump to Manjaro

**Comment by joseph9991** [comment]
> Indeed, ubuntu software does not support any theme that is not included by ubuntu. And not only ubuntu software, but actually any snap app. Ubuntu only gives one solution, and it is to create a new snap package just for the theme. It is a big pain in the ass because ubuntu changed all of its apps to snaps.
> 
> There's lots of people complaining about this, and unfortunately I don't have the time to create a snap package (and having to install the theme twice makes no sense anyway).
> 
> So I can only recommend you one thing, and it is to get rid of snaps and install gnome-software or synaptic:
> https://www.kevin-custer.com/blog/disabling-snaps-in-ubuntu-20-04/
> 
> I also recommend using PopOS rather than ubuntu, which is ubuntu-based but "done right", or just jump to Manjaro

I think I will stick to snap store. I just wanted to point out that it doesn't work for Snap on Ubuntu 20 and you have addressed the issue. So, I will close this issue!
